name = "spotify-loop-backend"
main = "src/index.ts"
compatibility_date = "2024-12-24"



[vars]
SUPABASE_ANON_KEY = 'https://fnozrjnxuszijdyqzenb.supabase.co'
SUPABASE_URL = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZub3pyam54dXN6aWpkeXF6ZW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMTEzODgsImV4cCI6MjA1MDU4NzM4OH0.KBiXx3WLcAYiDCgyjS3r3No-BQQTUuwUd3wUgZJ6qtY'

ENVIRONMENT = "production"

[env.dev]
vars = { ENVIRONMENT = "development" }


